try{
       const a=1;
       const c=(a+b);
       console.log(`c:${c}`);
}
catch(err){
      console.log(`err:${err}`);
}
finally{
        console.log(`Finally this is executed`);
      }

//Like try,catch and finally in JS Exceptional Handling.